In [6]:
import keras
import pandas as pd
import numpy as np
import cv2 as cv
import os

In [17]:
from keras.models import Sequential
from keras.layers import Dense, Embedding
from keras.layers import LSTM
from keras.callbacks import EarlyStopping

max_features = 4 # 0,1,2,3 (total of 4)

x = [
    [[0],[1],[1],[0],[0],[0]],
    [[0],[0],[0],[2],[2],[0]],
    [[0],[0],[0],[0],[3],[3]],
    [[0],[2],[2],[0],[0],[0]],
    [[0],[0],[3],[3],[0],[0]],
    [[0],[0],[0],[0],[1],[1]],
    [[1],[2],[1],[0],[0],[0]],
    [[0],[0],[3],[0],[0],[0]],
    [[0],[0],[0],[2],[1],[2]],
    [[0],[0],[0],[0],[0],[0]]
]
x = np.array(x,dtype=np.float32)
y = np.array([1,2,3,2,3,1,2,3,1,0],dtype=np.int32)

# Convert y2 to dummy variables
y2 = np.zeros((y.shape[0], max_features),dtype=np.float32)
y2[np.arange(y.shape[0]), y] = 1.0
print(y2)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [18]:
print("Build model...")
model = Sequential()
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2, input_shape=(None, 1)))
model.add(Dense(64, activation='sigmoid'))
model.add(Dense(4, activation='sigmoid'))

# try using different optimizers and different optimizer configs
model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

Build model...


In [19]:
print('Train...')
model.fit(x,y2,epochs=200)
pred = model.predict(x)
predict_classes = np.argmax(pred,axis=1)
print("Predicted classes: {}",predict_classes)
print("Expected classes: {}",predict_classes)

Train...
Epoch 1/200
10/10 [==============================] - 2s 153ms/step - loss: 0.8750 - acc: 0.4500
Epoch 2/200
10/10 [==============================] - 0s 1ms/step - loss: 0.8600 - acc: 0.4500
Epoch 3/200
10/10 [==============================] - 0s 998us/step - loss: 0.8478 - acc: 0.4500
Epoch 4/200
10/10 [==============================] - 0s 1ms/step - loss: 0.8321 - acc: 0.4500
Epoch 5/200
10/10 [==============================] - 0s 2ms/step - loss: 0.8186 - acc: 0.4500
Epoch 6/200
10/10 [==============================] - 0s 3ms/step - loss: 0.8095 - acc: 0.4500
Epoch 7/200
10/10 [==============================] - 0s 2ms/step - loss: 0.7999 - acc: 0.4500
Epoch 8/200
10/10 [==============================] - 0s 2ms/step - loss: 0.7766 - acc: 0.4500
Epoch 9/200
10/10 [==============================] - 0s 2ms/step - loss: 0.7684 - acc: 0.4500
Epoch 10/200
10/10 [==============================] - 0s 2ms/step - loss: 0.7572 - acc: 0.4500
Epoch 11/200
10/10 [==========================

Epoch 87/200
10/10 [==============================] - 0s 1ms/step - loss: 0.4527 - acc: 0.7500
Epoch 88/200
10/10 [==============================] - 0s 1ms/step - loss: 0.4591 - acc: 0.7500
Epoch 89/200
10/10 [==============================] - 0s 1ms/step - loss: 0.4992 - acc: 0.7500
Epoch 90/200
10/10 [==============================] - 0s 2ms/step - loss: 0.4985 - acc: 0.7500
Epoch 91/200
10/10 [==============================] - 0s 2ms/step - loss: 0.4875 - acc: 0.7500
Epoch 92/200
10/10 [==============================] - 0s 1ms/step - loss: 0.5244 - acc: 0.7500
Epoch 93/200
10/10 [==============================] - 0s 3ms/step - loss: 0.4801 - acc: 0.7500
Epoch 94/200
10/10 [==============================] - 0s 1ms/step - loss: 0.4767 - acc: 0.7500
Epoch 95/200
10/10 [==============================] - 0s 945us/step - loss: 0.4520 - acc: 0.7500
Epoch 96/200
10/10 [==============================] - 0s 1ms/step - loss: 0.4725 - acc: 0.7500
Epoch 97/200
10/10 [============================

10/10 [==============================] - 0s 1ms/step - loss: 0.3428 - acc: 0.8750
Epoch 173/200
10/10 [==============================] - 0s 1ms/step - loss: 0.3847 - acc: 0.8750
Epoch 174/200
10/10 [==============================] - 0s 324us/step - loss: 0.4075 - acc: 0.8250
Epoch 175/200
10/10 [==============================] - 0s 608us/step - loss: 0.5208 - acc: 0.8000
Epoch 176/200
10/10 [==============================] - 0s 1ms/step - loss: 0.4196 - acc: 0.8250
Epoch 177/200
10/10 [==============================] - 0s 2ms/step - loss: 0.3740 - acc: 0.8750
Epoch 178/200
10/10 [==============================] - 0s 2ms/step - loss: 0.4350 - acc: 0.8250
Epoch 179/200
10/10 [==============================] - 0s 2ms/step - loss: 0.4143 - acc: 0.8500
Epoch 180/200
10/10 [==============================] - 0s 2ms/step - loss: 0.5146 - acc: 0.7500
Epoch 181/200
10/10 [==============================] - 0s 1ms/step - loss: 0.3469 - acc: 0.9000
Epoch 182/200
10/10 [=============================

In [21]:
def runit(model, inp):
    inp = np.array(inp,dtype=np.float32)
    pred = model.predict(inp)
    return np.argmax(pred[0])

print( runit( model, [[[0],[1],[3],[1],[0],[0]]] ))

2
